ARG CADDY_VERSION=2.5.1

FROM caddy:${CADDY_VERSION}-builder AS builder

RUN xcaddy build \
      --with github.com/gamalan/caddy-tlsredis

FROM caddy:${CADDY_VERSION}

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
