services:
    limo-proxy:
        image: ethdotlimo/chauffeur
        depends_on:
          - redis
          - ethereum
        environment:
          - REDIS_URL=redis://redis:6379
          - DOMAIN_TLD=.local
          - ETH_RPC_ENDPOINT=${ETH_RPC_ENDPOINT-http://ethereum:8545}
          - IPFS_TARGET=http://ipfs:8080
        networks:
            limo:
        
    limo-caddy:
        build:
            context: .
            dockerfile: Dockerfile.caddy
        command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile.json"]
        networks:
            limo:
        ports:
          - "172.28.0.1:443:443"
        volumes:
          - ./Caddyfile.json:/etc/caddy/Caddyfile.json
          - caddy-data:/data
          - type: tmpfs
            target: /tmp
    
    ethereum:
        image: ethereum/client-go
        command: [ "--syncmode", "light", "--http", "--http.api", "eth,net,web3", "--http.addr", "ethereum", "--http.vhosts", "*" ]
        networks:
            limo:
        ports:
          - "172.28.0.1:8545:8545"
        volumes:
          - ethereum-data:/root/.ethereum
    
    ipfs:
        image: ipfs/kubo
        networks:
            limo:
        volumes:
          - ./ipfs-init.sh:/container-init.d/00-limo.sh
          - ipfs-data:/data/ipfs
    
    redis:
        image: redis
        command: [ "redis-server", "--save", "60", "1" ]
        networks:
            limo:
        volumes:
          - redis-data:/data
  
    limo-dns:
        image: strm/dnsmasq
        networks:
            limo:
        ports:
          - "172.28.0.1:53:53"
        volumes:
          - ./dnsmasq.conf:/etc/dnsmasq.conf
        cap_add:
          - NET_ADMIN
volumes:
    caddy-data:
    ethereum-data:
    ipfs-data:
    redis-data:
          
networks:
    limo:
        driver: bridge
        ipam:
            config:
                - subnet: 172.28.0.0/16
                  gateway: 172.28.0.1
